//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public int invoiceID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
        public double unitPrice { get; set; }
        public string Note { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }

        public InvoiceLine(int invoiceID,int productID, int quantity, int unitPrice, string note)
        {
            this.invoiceID = invoiceID;
            this.productID = productID;
            this.quantity = quantity;
            this.unitPrice = unitPrice;
            this.Note = note;
        }

        public InvoiceLine (int productID, int quantity, int unitPrice, string note)
        {

            this.productID = productID;
            this.quantity = quantity;
            this.unitPrice = unitPrice;
            this.Note = note;
        }
    }
}
