//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        private int nextInvoice;
        private int price;
        private string v;

        public InvoiceLine(int nextInvoice, int productID, int quantity, int price, string v)
        {
            this.nextInvoice = nextInvoice;
            this.productID = productID;
            this.quantity = quantity;
            this.price = price;
            this.v = v;
        }

        public InvoiceLine()
        {
        }

        public int invoiceID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
        public double unitPrice { get; set; }
        public string Note { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
