//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InvoiceLines = new HashSet<InvoiceLine>();
        }
    
        public int productID { get; set; }
        public int shopID { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public double price { get; set; }
        public string productType { get; set; }
        public string description { get; set; }
        public string OS { get; set; }
        public string screen { get; set; }
        public string camera { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string PIN { get; set; }
        public string SIM { get; set; }
        public string innerMemory { get; set; }
        public string manufacture { get; set; }
        public string guarantee { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
    }
}
